### ISSUE TITLE
运行直接报错了，LZ能帮忙看下么。

### ISSUE THREAD

**Issue by IMJacky** [pjmike/springboot-rpc-demo#6]
Exception in thread "main" java.lang.NullPointerException
	at com.pjmike.client.netty.ClientHandler.getRpcResponse(ClientHandler.java:53)
	at com.pjmike.client.netty.NettyClient.send(NettyClient.java:102)
	at com.pjmike.client.proxy.RpcClientDynamicProxy.invoke(RpcClientDynamicProxy.java:54)
	at com.sun.proxy.$Proxy37.hello(Unknown Source)
	at com.pjmike.client.ClientApplication.main(ClientApplication.java:18)

**Comment by Faoin** [comment]
按照代码的逻辑，client启动的时候需要加 sync() 阻塞Object.wait，等待异步的 socket 绑定事件完成代码。
`private void connect(Bootstrap bootstrap, String host, int port, int retry) {
        ChannelFuture channelFuture = null;
        try {
            channelFuture = bootstrap.connect(host, port).addListener(future -> {
                if (future.isSuccess()) {
                    log.info("连接服务端成功");
                } else if (retry == 0) {
                    log.error("重试次数已用完，放弃连接");
                } else {
                    //第几次重连：
                    int order = (MAX_RETRY - retry) + 1;
                    //本次重连的间隔
                    int delay = 1 << order;
                    log.error("{} : 连接失败，第 {} 重连....", new Date(), order);
                    bootstrap.config().group().schedule(() -> connect(bootstrap, host, port, retry - 1), delay, TimeUnit.SECONDS);
                }
            }).sync();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        channel = channelFuture.channel();
    }`

**Comment by Faoin** [comment]
按照代码的逻辑，client启动的时候需要加 sync() 阻塞Object.wait，等待异步的 socket 绑定事件完成代码。直接在失败重连那边加上就好

**Comment by IMJacky** [comment]
> 按照代码的逻辑，client启动的时候需要加 sync() 阻塞Object.wait，等待异步的 socket 绑定事件完成代码。直接在失败重连那边加上就好

是滴，没错，就是LZ注释掉的那行代码   bootstrap.connect(host, port).sync()

**Comment by dwdw666** [comment]
hi，我在加上了这个代码之后任然报错 了 Failed to initialize a channel  ，详细信息为 com.pjmike.client.netty.ClientHandler is not a @Sharable handler, so can't be added or removed multiple times

**Comment by dwdw666** [comment]
> 

这个问题是因为java版本的问题，当我切换到jdk1.8就没有问题了
